-- Удаляем существующую таблицу
DROP TABLE IF EXISTS car_services;

-- Создаем новую таблицу
CREATE TABLE car_services (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Основная информация о клиенте
  name text not null,
  phone text not null,
  
  -- Информация об автомобиле
  car_brand text not null,
  car_number text not null,
  current_mileage integer not null,
  
  -- История обслуживания
  last_service_date date,
  oil_type text,
  last_service_mileage integer,
  recommended_interval integer,
  
  -- Информация о текущем визите
  service_date date not null,
  work_types text[] not null,
  additional_work text,
  master_notes text,
  
  -- Системные поля
  user_id uuid references auth.users,
  status text default 'pending'
);

-- Индексы для оптимизации поиска
CREATE INDEX car_services_car_number_idx ON car_services(car_number);
CREATE INDEX car_services_phone_idx ON car_services(phone);
CREATE INDEX car_services_service_date_idx ON car_services(service_date);

-- Добавляем политики RLS
ALTER TABLE car_services ENABLE ROW LEVEL SECURITY;

-- Разрешаем анонимную вставку записей
CREATE POLICY "Allow anonymous inserts to car_services"
  ON car_services
  FOR INSERT
  WITH CHECK (true);

-- Разрешаем чтение своих записей по номеру телефона
CREATE POLICY "Allow select own records"
  ON car_services
  FOR SELECT
  USING (phone = current_user_identifier());

-- Комментарии к таблице
COMMENT ON TABLE car_services IS 'Записи на техническое обслуживание';
COMMENT ON COLUMN car_services.status IS 'Статус записи: pending, confirmed, completed, cancelled';
